name: CREATE TABLE - shopify_daily_stats
run-name: ${{ github.actor }} - CREATE TABLE - shopify_daily_stats
on: 
  push:
    paths:
      - '**/create_table/shopify_customer_log/**'
      - '**/workflows/shopify_customer_log.yml'
      

jobs:
  create_shopify_daily_stats:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo code
        uses: actions/checkout@v3
      - run: echo "${{ github.repository }} repository has been cloned to the runner. The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - name: Set up Python environment
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r create_table/requirements.txt
    
      - name: CREATE TABLE - shopify_daily_stats
        env: 
          AWS_ACCESS_KEY:  ${{ secrets.AWS_ACCESS_KEY }}
          AWS_ACCESS_SECRET: ${{ secrets.AWS_ACCESS_SECRET }}
        run: python create_table/shopify_daily_stats/create_table.py 

      - run: echo "Job status - ${{ job.status }}."
